# Setup
title:               ariuka
tagline:             ''
description:         'testing 1212'
url:                 https://eariunbayar.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ariunbayar Enkhtaivan
  url:               https://instagram.com/ariunbayar_e
  email:             ariunbayarenkhtaivan@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
